name: Send Email via AWS SES
description: Send Email via AWS SES

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  bcc:
    description: 'Email address of the BCC recipient'
    required: false
  body:
    description: 'Body of the email'
    required: false
  body_html:
    description: 'Body of the email in HTML format'
    required: false
  cc:
    description: 'Email address of the CC recipient'
    required: false
  from:
    description: 'Email address of the sender'
    required: true
  reply_to:
    description: 'Email address to reply to'
    required: false
  subject:
    description: 'Subject of the email'
    required: true
  to:
    description: 'Email address of the recipient'
    required: true

runs:
  using: node16
  main: index.js

branding:
  color: blue
  icon: mail
